backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Crear {{collection}} \"{{slug}}\""
    update: "Actualizar {{collection}} \"{{slug}}\""
    delete: "Eliminar {{collection}} \"{{slug}}\""
    uploadMedia: "Subir [media]"
    deleteMedia: "Eliminar [media]"

media_folder: "static/uploads"
public_folder: "/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey"

collections:
  - name: "posts"
    label: "Publicaciones"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha",   name: "date",   widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Autor",   name: "author", widget: "string" }
      - { label: "Etiquetas", name: "tags", widget: "list", default: [] }
      - { label: "Imagen de portada", name: "cover", widget: "image", allow_multiple: false }
      - { label: "Cuerpo",  name: "body",   widget: "markdown" }