backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Crear {{collection}} \"{{slug}}\""
    update: "Actualizar {{collection}} \"{{slug}}\""
    delete: "Eliminar {{collection}} \"{{slug}}\""
    uploadMedia: "Subir [media]"
    deleteMedia: "Eliminar [media]"

media_folder: "static/uploads"
public_folder: "/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey"

collections:
  - name: "posts"
    label: "Publicaciones"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }